### ISSUE TITLE
wg blocks forever?

### ISSUE THREAD

**Issue by embano1** [phoban01/streaming-unzipper#1]
Thx for the example :)

Just two observations glancing over the code:

I don't see `wg.Done()` being called at all?
https://github.com/phoban01/streaming-unzipper/blob/d71053bb497ccb7dc459c9f5f97e26127599f5b1/main.go#L110

Errors from goroutines, e.g. `go unzip()` are not handled (err is always nil), so the returned `error` from these functions is not really useful :)

**Comment by phoban01** [comment]
Hey Michael @embano1,

Thanks for looking over the code and for comments, I appreciate it! 

Yup well spotted on both counts. I have updated the example.
